application: kancolledb-project
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /webapp/static
  static_dir: static

- url: /.*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: kancolledb-project:australia-southeast1:kancolle-mysql
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: kancolledbpw

libraries:
- name: MySQLdb
  version: latest
# - name: PIL
#   version: latest
# - name: pycrypto
#   version: latest
# - name: grpcio
#   version: latest

# skips the env files when uploading to gcloud, as it is only required locally for virtualenv
# skip_files:
#  - ^env
