runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /webapp/static
  static_dir: static

- url: /.*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: kancolledb-project:australia-southeast1:kancolle-mysql
    CLOUDSQL_USER: root
    CLOUDSQL_PASSWORD: kancolledbpw

libraries:
- name: MySQLdb
  version:
- name: Bcrypt
  verison:
- name: PIL
  version:
